### ISSUE TITLE
连接提示

### ISSUE THREAD

**Issue by zfms4188** [SmallJiu/MirageInterface#2]
无象接口放置一些后
很容易忘记这个接口到底连接了什么机器了 有没有办法进行提示？
例如 渲染一条粒子链接至对应方块 或 top检测器提示方块位置名称 waila？等等

**Comment by SmallJiu** [comment]
> 无象接口放置一些后
> 很容易忘记这个接口到底连接了什么机器了 有没有办法进行提示？
> 例如 渲染一条粒子链接至对应方块 或 top检测器提示方块位置名称 waila？等等

可以，这个功能会跟另一个issue一起添加到下个版本

**Comment by SmallJiu** [comment]
已完成，请查看mcmod下载页或者github的Releases

**Comment by zfms4188** [comment]
> 已完成，请查看mcmod下载页或者github的Releases

未安装waila时客户端和服务端均启动时崩溃
（另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）

**Comment by SmallJiu** [comment]
> > 已完成，请查看mcmod下载页或者github的Releases
> 
> 未安装waila时客户端和服务端均启动时崩溃
> （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）

好了，版本号是1.0.1-a1

**Comment by zfms4188** [comment]
> > > 已完成，请查看mcmod下载页或者github的Releases
> > 
> > 
> > 未安装waila时客户端和服务端均启动时崩溃
> > （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）
> 
> 好了，版本号是1.0.1-a1

好！目前看来一切正常,后续能否跟进top检测器兼容？

**Comment by SmallJiu** [comment]
> > > > 已完成，请查看mcmod下载页或者github的Releases
> > > 
> > > 
> > > 未安装waila时客户端和服务端均启动时崩溃
> > > （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）
> > 
> > 好了，版本号是1.0.1-a1
> 
> 好！目前看来一切正常,后续能否跟进top检测器兼容？

已兼容，版本号是1.0.1-a2
![U5)42U9)Z4S`O7H$`0E0V95.png](https://github.com/SmallJiu/MirageInterface/assets/70803028/a68ad40e-48e8-4424-82eb-c4c7a570358b)

**Comment by zfms4188** [comment]
> > > > > 已完成，请查看mcmod下载页或者github的Releases
> > > > 
> > > > 
> > > > 未安装waila时客户端和服务端均启动时崩溃
> > > > （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）
> > > 
> > > 
> > > 好了，版本号是1.0.1-a1
> > 
> > 
> > 好！目前看来一切正常,后续能否跟进top检测器兼容？
> 
> 已兼容，版本号是1.0.1-a2 ![U5)42U9)Z4SO7H$0E0V95.png](https://private-user-images.githubusercontent.com/70803028/333616873-a68ad40e-48e8-4424-82eb-c4c7a570358b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjE1MzAsIm5iZiI6MTcxNjU2MTIzMCwicGF0aCI6Ii83MDgwMzAyOC8zMzM2MTY4NzMtYTY4YWQ0MGUtNDhlOC00NDI0LTgyZWItYzRjN2E1NzAzNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTljZTVmYWRjNjhiZGI1YjY2NjA2MWQwYWI4MmNkZDNmNjc1ZWY3MDk1NTlhMjNjYmM2YTg0NjI1NzNjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nIJa5JhH19gbUy1vVRMSbm5BMf-4iDlCjy-gFvk3tgU)

单机测试一切正常,但服务端不兼容,检测器显示 "Error"
使用top检测器:https://www.mcmod.cn/class/9882.html
服务端使用 catserver

另外一个新问题: 服务端连接器右键方块但未绑定至连接器时,鼠标查看连接器后,客户端崩溃
客户端报错:https://pastebin.com/hq4cVb4T
(pcl崩溃提示和hei不兼容,个人觉得大概不是)

**Comment by SmallJiu** [comment]
> > > > > > 已完成，请查看mcmod下载页或者github的Releases
> > > > > 
> > > > > 
> > > > > 未安装waila时客户端和服务端均启动时崩溃
> > > > > （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）
> > > > 
> > > > 
> > > > 好了，版本号是1.0.1-a1
> > > 
> > > 
> > > 好！目前看来一切正常,后续能否跟进top检测器兼容？
> > 
> > 已兼容，版本号是1.0.1-a2 ![U5)42U9)Z4SO7H$0E0V95.png](https://private-user-images.githubusercontent.com/70803028/333616873-a68ad40e-48e8-4424-82eb-c4c7a570358b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjE1MzAsIm5iZiI6MTcxNjU2MTIzMCwicGF0aCI6Ii83MDgwMzAyOC8zMzM2MTY4NzMtYTY4YWQ0MGUtNDhlOC00NDI0LTgyZWItYzRjN2E1NzAzNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTljZTVmYWRjNjhiZGI1YjY2NjA2MWQwYWI4MmNkZDNmNjc1ZWY3MDk1NTlhMjNjYmM2YTg0NjI1NzNjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nIJa5JhH19gbUy1vVRMSbm5BMf-4iDlCjy-gFvk3tgU)
> 
> 单机测试一切正常,但服务端不兼容,检测器显示 "Error"
> 使用top检测器:https://www.mcmod.cn/class/9882.html
> 服务端使用 catserver
> 
> 另外一个新问题: 服务端连接器右键方块但未绑定至连接器时,鼠标查看连接器后,客户端崩溃
> 客户端报错:https://pastebin.com/hq4cVb4T
> (pcl崩溃提示和hei不兼容,个人觉得大概不是)

第一个问题：能否看下后台
第二个问题已解决

**Comment by SmallJiu** [comment]
> > > > > > 已完成，请查看mcmod下载页或者github的Releases
> > > > > 
> > > > > 
> > > > > 未安装waila时客户端和服务端均启动时崩溃
> > > > > （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）
> > > > 
> > > > 
> > > > 好了，版本号是1.0.1-a1
> > > 
> > > 
> > > 好！目前看来一切正常,后续能否跟进top检测器兼容？
> > 
> > 已兼容，版本号是1.0.1-a2 ![U5)42U9)Z4SO7H$0E0V95.png](https://private-user-images.githubusercontent.com/70803028/333616873-a68ad40e-48e8-4424-82eb-c4c7a570358b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjE1MzAsIm5iZiI6MTcxNjU2MTIzMCwicGF0aCI6Ii83MDgwMzAyOC8zMzM2MTY4NzMtYTY4YWQ0MGUtNDhlOC00NDI0LTgyZWItYzRjN2E1NzAzNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTljZTVmYWRjNjhiZGI1YjY2NjA2MWQwYWI4MmNkZDNmNjc1ZWY3MDk1NTlhMjNjYmM2YTg0NjI1NzNjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nIJa5JhH19gbUy1vVRMSbm5BMf-4iDlCjy-gFvk3tgU)
> 
> 单机测试一切正常,但服务端不兼容,检测器显示 "Error"
> 使用top检测器:https://www.mcmod.cn/class/9882.html
> 服务端使用 catserver
> 
> 另外一个新问题: 服务端连接器右键方块但未绑定至连接器时,鼠标查看连接器后,客户端崩溃
> 客户端报错:https://pastebin.com/hq4cVb4T
> (pcl崩溃提示和hei不兼容,个人觉得大概不是)

自己双开了下，应该是可以了
![@`)_)UD21KEY`X9DZ1S9}TI.png](https://github.com/SmallJiu/MirageInterface/assets/70803028/734662cb-1d01-44ae-85e7-0aeac6d65235)

**Comment by SmallJiu** [comment]
> > > > > > 已完成，请查看mcmod下载页或者github的Releases
> > > > > 
> > > > > 
> > > > > 未安装waila时客户端和服务端均启动时崩溃
> > > > > （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）
> > > > 
> > > > 
> > > > 好了，版本号是1.0.1-a1
> > > 
> > > 
> > > 好！目前看来一切正常,后续能否跟进top检测器兼容？
> > 
> > 已兼容，版本号是1.0.1-a2 ![U5)42U9)Z4SO7H$0E0V95.png](https://private-user-images.githubusercontent.com/70803028/333616873-a68ad40e-48e8-4424-82eb-c4c7a570358b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjE1MzAsIm5iZiI6MTcxNjU2MTIzMCwicGF0aCI6Ii83MDgwMzAyOC8zMzM2MTY4NzMtYTY4YWQ0MGUtNDhlOC00NDI0LTgyZWItYzRjN2E1NzAzNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTljZTVmYWRjNjhiZGI1YjY2NjA2MWQwYWI4MmNkZDNmNjc1ZWY3MDk1NTlhMjNjYmM2YTg0NjI1NzNjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nIJa5JhH19gbUy1vVRMSbm5BMf-4iDlCjy-gFvk3tgU)
> 
> 单机测试一切正常,但服务端不兼容,检测器显示 "Error"
> 使用top检测器:https://www.mcmod.cn/class/9882.html
> 服务端使用 catserver
> 
> 另外一个新问题: 服务端连接器右键方块但未绑定至连接器时,鼠标查看连接器后,客户端崩溃
> 客户端报错:https://pastebin.com/hq4cVb4T
> (pcl崩溃提示和hei不兼容,个人觉得大概不是)

已覆盖mcmod的1.0.1-a2的mod文件

**Comment by zfms4188** [comment]
> > > > > > > 已完成，请查看mcmod下载页或者github的Releases
> > > > > > 
> > > > > > 
> > > > > > 未安装waila时客户端和服务端均启动时崩溃
> > > > > > （另外再填一个waila词条？ “已绑定至 dim x y z 的 xxx 容器”）
> > > > > 
> > > > > 
> > > > > 好了，版本号是1.0.1-a1
> > > > 
> > > > 
> > > > 好！目前看来一切正常,后续能否跟进top检测器兼容？
> > > 
> > > 
> > > 已兼容，版本号是1.0.1-a2 ![U5)42U9)Z4SO7H$0E0V95.png](https://private-user-images.githubusercontent.com/70803028/333616873-a68ad40e-48e8-4424-82eb-c4c7a570358b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NjE1MzAsIm5iZiI6MTcxNjU2MTIzMCwicGF0aCI6Ii83MDgwMzAyOC8zMzM2MTY4NzMtYTY4YWQ0MGUtNDhlOC00NDI0LTgyZWItYzRjN2E1NzAzNThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDE0MzM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYTljZTVmYWRjNjhiZGI1YjY2NjA2MWQwYWI4MmNkZDNmNjc1ZWY3MDk1NTlhMjNjYmM2YTg0NjI1NzNjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nIJa5JhH19gbUy1vVRMSbm5BMf-4iDlCjy-gFvk3tgU)
> > 
> > 
> > 单机测试一切正常,但服务端不兼容,检测器显示 "Error"
> > 使用top检测器:https://www.mcmod.cn/class/9882.html
> > 服务端使用 catserver
> > 另外一个新问题: 服务端连接器右键方块但未绑定至连接器时,鼠标查看连接器后,客户端崩溃
> > 客户端报错:https://pastebin.com/hq4cVb4T
> > (pcl崩溃提示和hei不兼容,个人觉得大概不是)
> 
> 已覆盖mcmod的1.0.1-a2的mod文件

服务端top检测器测试正常
