### ISSUE TITLE
高版本更新可能

### ISSUE THREAD

**Issue by TheDesiringOne** [SmallJiu/MirageInterface#5]
有计划更新到高版本，比如1.20.1吗？

**Comment by SmallJiu** [comment]
> 有计划更新到高版本，比如1.20.1吗？

幻灵接口还没有高版本的嘛

**Comment by TheDesiringOne** [comment]
有，但那个的版本貌似要很多前置，而且我觉得这个版本更好用，如果没空就算了吧，不管怎么说谢谢回复了。
